const { onCall, HttpsError } = require('firebase-functions/v2/https');
const admin = require('firebase-admin');
const db = admin.firestore();
const F = admin.firestore.FieldValue;
function uidOf(req) { if (!req.auth) throw new HttpsError('unauthenticated', 'Sign-in required.'); return req.auth.uid; }
function adminOnly(req) { const uid = uidOf(req); if (req.auth.token?.admin !== true) throw new HttpsError('permission-denied', 'Admin access required.'); return uid; }
async function active(uid, req) { const d = await db.collection('users').doc(uid).get(); const x = d.data() || {}; if (!d.exists || x.profileActive !== true || x.discoverable !== true || x.termsAccepted !== true || x.intentConfirmed !== true) throw new HttpsError('failed-precondition', 'An active Nikah profile is required.'); if (req.auth.token?.email_verified !== true) throw new HttpsError('failed-precondition', 'Email verification is required.'); return d; }
function pair(a, b) { return a < b ? `${a}_${b}` : `${b}_${a}`; }
exports.unblockUser = onCall(async (req) => { const uid = uidOf(req), other = String(req.data?.blockedUid || ''); if (!other || other === uid) throw new HttpsError('invalid-argument', 'Invalid member.'); await active(uid, req); const ref = db.collection('blocks').doc(pair(uid, other)); const snap = await ref.get(); if (!snap.exists || snap.data()?.blockerUid !== uid) throw new HttpsError('permission-denied', 'Only the member who created this block can remove it.'); await ref.delete(); const c = db.collection('connections').doc(pair(uid, other)); const cs = await c.get(); if (cs.exists && cs.data()?.status === 'blocked' && cs.data()?.blockedBy === uid) await c.update({ status: 'active', blockedBy: F.delete(), blockedAt: F.delete(), updatedAt: F.serverTimestamp() }); return { unblocked: true }; });
exports.listMyCommunityMutes = onCall(async (req) => { const uid = uidOf(req); await active(uid, req); const snap = await db.collection('users').doc(uid).collection('communityMutes').limit(100).get(); return { mutedUids: snap.docs.map(d => d.id) }; });
exports.unmuteCommunityUser = onCall(async (req) => { const uid = uidOf(req), other = String(req.data?.targetUid || ''); if (!other || other === uid) throw new HttpsError('invalid-argument', 'Invalid member.'); await active(uid, req); await db.collection('users').doc(uid).collection('communityMutes').doc(other).delete(); return { muted: false }; });
exports.submitCommunityReport = onCall(async (req) => { const uid = uidOf(req), messageId = String(req.data?.messageId || ''), reportedUid = String(req.data?.reportedUid || ''), reason = String(req.data?.reason || '').trim().slice(0, 120); if (!messageId || !reportedUid || reportedUid === uid || !reason) throw new HttpsError('invalid-argument', 'Report details are required.'); await active(uid, req); const message = await db.collection('communityMessages').doc(messageId).get(); if (!message.exists || message.data()?.authorUid !== reportedUid) throw new HttpsError('not-found', 'Community message not found.'); const ref = db.collection('reports').doc(); await ref.set({ reporterUid: uid, reportedUid, reason, targetType: 'communityMessage', targetMessageId: messageId, status: 'pending', createdAt: F.serverTimestamp() }); await db.collection('moderationQueue').doc(ref.id).set({ reportId: ref.id, reporterUid: uid, reportedUid, reason, targetType: 'communityMessage', targetMessageId: messageId, status: 'pending', createdAt: F.serverTimestamp() }, { merge: true }); return { reported: true, reportId: ref.id }; });
exports.moderateCommunityMessage = onCall(async (req) => { const moderatorUid = adminOnly(req), messageId = String(req.data?.messageId || ''), reportId = String(req.data?.reportId || ''), decision = String(req.data?.decision || ''); if (!messageId || !['remove', 'restore', 'dismiss'].includes(decision)) throw new HttpsError('invalid-argument', 'Invalid moderation action.'); const msg = db.collection('communityMessages').doc(messageId), snap = await msg.get(); if (!snap.exists && decision !== 'remove') throw new HttpsError('not-found', 'Message not found.'); if (decision === 'remove') await msg.set({ moderationStatus: 'removed', moderatedBy: moderatorUid, moderatedAt: F.serverTimestamp() }, { merge: true }); if (decision === 'restore') await msg.set({ moderationStatus: F.delete(), moderatedBy: moderatorUid, moderatedAt: F.serverTimestamp() }, { merge: true }); if (reportId) await db.collection('moderationQueue').doc(reportId).set({ status: decision === 'dismiss' ? 'dismissed' : 'actioned', moderatorUid, decidedAt: F.serverTimestamp() }, { merge: true }); return { moderated: true, decision }; });
