const matches=[['Ayesha',29,'Pakistan','Family-oriented and looking for a sincere marriage.'],['Sara',27,'Saudi Arabia','Values honesty, respect and family.'],['Hiba',30,'Germany','Interested in a serious marriage.']];
const communitySeed=[['Amina','🇬🇧','Welcome everyone. May Allah make this community beneficial.'],['Ahmed','🇸🇦','Assalamualaikum everyone!'],['Fatima','🇵🇰','Looking for respectful conversations about marriage and family.']];
function show(id){document.querySelectorAll('section').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');scrollTo(0,0);if(id==='matches')render();if(id==='community')renderCommunity()}
function home(){show('home')}
function save(){let n=name.value.trim(),a=age.value.trim(),c=country.value.trim();if(!n||!a||!c){alert('Please enter name, age and country.');return}localStorage.setItem('bnb',JSON.stringify({n,a,c,about:about.value}));alert('Profile saved!');show('matches')}
function render(){list.innerHTML=matches.map(m=>`<div class="match"><h3>👤 ${m[0]}, ${m[1]}</h3><div class="muted">${m[2]}</div><p>${m[3]}</p><button onclick="alert('Interest sent to ${m[0]} (MVP demo).')">♡ Express Interest</button></div>`).join('')}
function getCommunityMessages(){try{return JSON.parse(localStorage.getItem('bnbCommunity')||'[]')}catch(e){return[]}}
function renderCommunity(){let all=[...communitySeed,...getCommunityMessages()];chatMessages.innerHTML=all.map(m=>`<div class="chat-message"><div><strong>${escapeHtml(m[0])}</strong> <span>${escapeHtml(m[1]||'🌍')}</span></div><p>${escapeHtml(m[2])}</p></div>`).join('');chatMessages.scrollTop=chatMessages.scrollHeight}
function sendCommunityMessage(){let text=chatInput.value.trim();if(!text)return;if(/(whatsapp|telegram|phone\s*number|\+?\d[\d\s-]{7,})/i.test(text)){alert('For your safety, please do not share phone numbers or private contact details in the community room.');return}let n=(JSON.parse(localStorage.getItem('bnb')||'{}').n)||'Member';let msgs=getCommunityMessages();msgs.push([n,'🌍',text]);localStorage.setItem('bnbCommunity',JSON.stringify(msgs.slice(-100)));chatInput.value='';renderCommunity()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
chatInput?.addEventListener('keydown',e=>{if(e.key==='Enter')sendCommunityMessage()});
