const { app } = require("@azure/functions");
const { getPool, query } = require("./db");
const { requireAuth } = require("./auth");

const PLAN_VALUES = { premium_basic_20: 2000, premium_plus_40: 4000, premium_vip_60: 6000 };
const OWNER_WALLET_ROUTE_VERSION = "2026-09-23-owner-live";
const clean=(v,max)=>typeof v==="string"?v.trim().slice(0,max):"";
function moneyMinor(v){const n=Number(v);if(!Number.isFinite(n)||n<=0||n>1000000000)throw Object.assign(new Error("INVALID_AMOUNT"),{statusCode:400});return Math.round(n*100);}
function currency(v){const c=clean(v,10).toUpperCase();if(!["SAR","USD","PKR","USDT"].includes(c))throw Object.assign(new Error("UNSUPPORTED_CURRENCY"),{statusCode:400});return c;}
function validDestination(c,v){const d=clean(v,300);if(d.length<6)return false;if(c==="USDT"&&!(/^(T[1-9A-HJ-NP-Za-km-z]{33}|0x[a-fA-F0-9]{40})$/.test(d)))return false;return true;}
async function admin(user){const r=await query("SELECT id,role,status FROM users WHERE (azure_subject=$1 OR firebase_uid=$1) AND status='active' LIMIT 1",[user.azure_subject||user.uid]);if(!r.rows[0]||!["admin","moderator"].includes(r.rows[0].role))throw Object.assign(new Error("ADMIN_REQUIRED"),{statusCode:403});return r.rows[0];}

app.http("ownerEarningsDashboardAzure",{methods:["GET"],authLevel:"anonymous",route:"admin/owner/earnings",handler:requireAuth(async(request,context,user)=>{
 try{await admin(user);const [s,rows,plans,settlements,providerPayouts]=await Promise.all([
  query("SELECT * FROM owner_earnings_summary WHERE id=true"),
  query("SELECT oe.id,oe.product_id,oe.order_id,oe.status,oe.plan_value_sar_minor,oe.created_at,oe.verified_at,u.azure_subject,u.email FROM owner_earnings oe LEFT JOIN users u ON u.id=oe.user_id ORDER BY oe.created_at DESC LIMIT 500"),
  query("SELECT plan_key,display_name,sort_order FROM premium_plans WHERE active=true ORDER BY sort_order"),
  query("SELECT id,currency,amount_minor,country,status,provider_reference,created_at,paid_at FROM owner_settlements ORDER BY created_at DESC LIMIT 100"),
  query("SELECT provider_reference,currency,amount_minor,provider,created_at FROM owner_provider_settlements ORDER BY created_at DESC LIMIT 100")
 ]);
 const x=s.rows[0]||{};const monthly={};const planCounts={};
 for(const r of rows.rows){const d=new Date(r.created_at);const m=isNaN(d)?'unknown':d.toISOString().slice(0,7);monthly[m]??={month:m,upgrades:0,planValueSar:0};monthly[m].upgrades++;monthly[m].planValueSar+=Number(r.plan_value_sar_minor||0)/100;planCounts[r.product_id]=(planCounts[r.product_id]||0)+1;}
 return {status:200,jsonBody:{ok:true,currentMonth:new Date().toISOString().slice(0,7),currentMonthUpgrades:monthly[new Date().toISOString().slice(0,7)]?.upgrades||0,currentMonthPlanValueSar:monthly[new Date().toISOString().slice(0,7)]?.planValueSar||0,totalVerifiedUpgrades:Number(x.verified_sales_count||0),totalVerifiedPlanValueSar:Number(x.verified_plan_value_sar_minor||0)/100,availableSar:Number(x.available_sar_minor||0)/100,availableUsd:Number(x.available_usd_minor||0)/100,availablePkr:Number(x.available_pkr_minor||0)/100,availableUsdt:Number(x.available_usdt_minor||0)/100,pendingSar:Number(x.pending_sar_minor||0)/100,pendingUsd:Number(x.pending_usd_minor||0)/100,pendingPkr:Number(x.pending_pkr_minor||0)/100,pendingUsdt:Number(x.pending_usdt_minor||0)/100,settledSar:Number(x.settled_sar_minor||0)/100,settledUsd:Number(x.settled_usd_minor||0)/100,settledPkr:Number(x.settled_pkr_minor||0)/100,settledUsdt:Number(x.settled_usdt_minor||0)/100,planCounts,plans:plans.rows,monthly:Object.values(monthly).sort((a,b)=>b.month.localeCompare(a.month)),sales:rows.rows,settlements:settlements.rows,providerPayouts:providerPayouts.rows,note:"Verified Google Play sales ledger values. Saudi merchant payouts are received by bank wire in USD and remain controlled by Google Play."}};}
 catch(e){context.error("OWNER_EARNINGS_DASHBOARD_FAILED",e);return {status:e.statusCode||500,jsonBody:{ok:false,error:e.statusCode?e.message:"OWNER_EARNINGS_DASHBOARD_FAILED"}};}
})});

app.http("ownerSettlementProfileAzure",{methods:["GET","POST"],authLevel:"anonymous",route:"admin/owner/settlement-profile",handler:requireAuth(async(request,context,user)=>{
 try{const a=await admin(user);if(request.method==="GET"){const r=await query("SELECT country,currency,destination,label,updated_at FROM owner_settlement_profile WHERE id=true");return {status:200,jsonBody:{ok:true,profile:r.rows[0]||null}};}
 const b=await request.json();const c=currency(b?.currency),country=clean(b?.country,100),destination=clean(b?.destination,300),label=clean(b?.label,80);if(!country||!label||!validDestination(c,destination))return {status:400,jsonBody:{ok:false,error:"INVALID_SETTLEMENT_PROFILE"}};
 await query("INSERT INTO owner_settlement_profile(id,country,currency,destination,label,updated_by,updated_at) VALUES(true,$1,$2,$3,$4,$5,now()) ON CONFLICT(id) DO UPDATE SET country=EXCLUDED.country,currency=EXCLUDED.currency,destination=EXCLUDED.destination,label=EXCLUDED.label,updated_by=EXCLUDED.updated_by,updated_at=now()",[country,c,destination,label,a.id]);
 return {status:200,jsonBody:{ok:true,saved:true,currency:c,country,label}};
 }catch(e){context.error("OWNER_PROFILE_FAILED",e);return {status:e.statusCode||500,jsonBody:{ok:false,error:e.statusCode?e.message:"OWNER_PROFILE_FAILED"}};}
})});

app.http("ownerProviderSettlementAzure",{methods:["POST"],authLevel:"anonymous",route:"admin/owner/provider-settlement",handler:requireAuth(async(request,context,user)=>{
 try{const a=await admin(user),b=await request.json(),c=currency(b?.currency),amount=moneyMinor(b?.amount),provider=clean(b?.provider,80),reference=clean(b?.providerReference,200);if(!provider||reference.length<3) return {status:400,jsonBody:{ok:false,error:"PROVIDER_REFERENCE_REQUIRED"}};
 const pool=getPool();const client=await pool.connect();try{await client.query("BEGIN");const old=await client.query("SELECT provider_reference FROM owner_provider_settlements WHERE provider_reference=$1",[reference]);if(old.rows.length){await client.query("ROLLBACK");return {status:409,jsonBody:{ok:false,error:"PROVIDER_REFERENCE_ALREADY_RECORDED"}};}
 const settledKey=c==="SAR"?"settled_sar_minor":c==="USD"?"settled_usd_minor":c==="PKR"?"settled_pkr_minor":"settled_usdt_minor";await client.query("INSERT INTO owner_provider_settlements(provider_reference,currency,amount_minor,provider,recorded_by) VALUES($1,$2,$3,$4,$5)",[reference,c,amount,provider,a.id]);await client.query("UPDATE owner_earnings_summary SET "+settledKey+"="+settledKey+"+$1,updated_at=now() WHERE id=true",[amount]);await client.query("COMMIT");return {status:200,jsonBody:{ok:true,recorded:true,received:true,amount:amount/100,currency:c,providerReference:reference}};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}
 }catch(e){context.error("OWNER_PROVIDER_SETTLEMENT_FAILED",e);return {status:e.statusCode||500,jsonBody:{ok:false,error:e.statusCode?e.message:"OWNER_PROVIDER_SETTLEMENT_FAILED"}};}
})});

app.http("ownerSettlementRequestAzure",{methods:["POST"],authLevel:"anonymous",route:"admin/owner/settlements",handler:requireAuth(async(request,context,user)=>{
 try{const a=await admin(user),b=await request.json(),c=currency(b?.currency),amount=moneyMinor(b?.amount),country=clean(b?.country,100),destination=clean(b?.destination,300);if(!country||!validDestination(c,destination))return {status:400,jsonBody:{ok:false,error:"INVALID_SETTLEMENT"}};
 const key=c==="SAR"?"available_sar_minor":c==="USD"?"available_usd_minor":c==="PKR"?"available_pkr_minor":"available_usdt_minor";const pending=c==="SAR"?"pending_sar_minor":c==="USD"?"pending_usd_minor":c==="PKR"?"pending_pkr_minor":"pending_usdt_minor";const pool=getPool(),client=await pool.connect();try{await client.query("BEGIN");const s=await client.query("SELECT "+key+" AS available,"+pending+" AS pending FROM owner_earnings_summary WHERE id=true FOR UPDATE");const av=Number(s.rows[0]?.available||0);if(amount>av){await client.query("ROLLBACK");return {status:409,jsonBody:{ok:false,error:"INSUFFICIENT_AVAILABLE_BALANCE"}};}const ins=await client.query("INSERT INTO owner_settlements(currency,amount_minor,country,destination,status,requested_by) VALUES($1,$2,$3,$4,'pending_provider',$5) RETURNING id,status,created_at",[c,amount,country,destination,a.id]);await client.query("UPDATE owner_earnings_summary SET "+key+"="+key+"-$1,"+pending+"="+pending+"+$1,updated_at=now() WHERE id=true",[amount]);await client.query("COMMIT");return {status:200,jsonBody:{ok:true,settlementId:ins.rows[0].id,status:ins.rows[0].status}};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}
 }catch(e){context.error("OWNER_SETTLEMENT_REQUEST_FAILED",e);return {status:e.statusCode||500,jsonBody:{ok:false,error:e.statusCode?e.message:"OWNER_SETTLEMENT_REQUEST_FAILED"}};}
})});

app.http("ownerSettlementPaidAzure",{methods:["PATCH"],authLevel:"anonymous",route:"admin/owner/settlements/{id}/paid",handler:requireAuth(async(request,context,user)=>{
 try{const a=await admin(user),b=await request.json(),ref=clean(b?.providerReference,200);if(ref.length<3)return {status:400,jsonBody:{ok:false,error:"PROVIDER_REFERENCE_REQUIRED"}};const pool=getPool(),client=await pool.connect();try{await client.query("BEGIN");const s=await client.query("SELECT currency,amount_minor,status FROM owner_settlements WHERE id=$1 FOR UPDATE",[request.params.id]);if(!s.rows[0]){await client.query("ROLLBACK");return {status:404,jsonBody:{ok:false,error:"SETTLEMENT_NOT_FOUND"}};}const x=s.rows[0];if(x.status!=="pending_provider"){await client.query("ROLLBACK");return {status:409,jsonBody:{ok:false,error:"SETTLEMENT_NOT_PENDING"}};}const c=x.currency,amount=Number(x.amount_minor);const pending=c==="SAR"?"pending_sar_minor":c==="USD"?"pending_usd_minor":c==="PKR"?"pending_pkr_minor":"pending_usdt_minor";const settled=c==="SAR"?"settled_sar_minor":c==="USD"?"settled_usd_minor":c==="PKR"?"settled_pkr_minor":"settled_usdt_minor";await client.query("UPDATE owner_settlements SET status='paid',provider_reference=$1,paid_by=$2,paid_at=now(),updated_at=now() WHERE id=$3",[ref,a.id,request.params.id]);await client.query("UPDATE owner_earnings_summary SET "+pending+"="+pending+"-$1,"+settled+"="+settled+"+$1,updated_at=now() WHERE id=true",[amount]);await client.query("COMMIT");return {status:200,jsonBody:{ok:true,paid:true,settlementId:request.params.id,providerReference:ref}};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}
 }catch(e){context.error("OWNER_SETTLEMENT_PAID_FAILED",e);return {status:e.statusCode||500,jsonBody:{ok:false,error:e.statusCode?e.message:"OWNER_SETTLEMENT_PAID_FAILED"}};}
})});
