package com.nikahbridge;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.text.InputType;
import android.view.Gravity;
import android.widget.*;
import com.google.firebase.auth.*;
import com.google.firebase.firestore.*;
import com.google.firebase.functions.FirebaseFunctions;
import java.util.*;

/** Best Nikah Bridge - real Firebase production client. No fake/demo profiles. */
public class ProductionMainActivity extends Activity {
    FirebaseAuth auth; FirebaseFirestore db; FirebaseFunctions fn; LinearLayout root;
    int green=Color.rgb(18,103,82), dark=Color.rgb(30,45,41), gray=Color.rgb(95,108,103);
    @Override public void onCreate(Bundle b){super.onCreate(b);auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance();fn=FirebaseFunctions.getInstance();if(auth.getCurrentUser()==null)authScreen();else home();}
    void base(){ScrollView s=new ScrollView(this);s.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,24,22,32);s.addView(root);setContentView(s);}
    TextView t(String x,int z,boolean bold){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(bold?dark:gray);v.setPadding(4,8,4,12);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    void title(String x){TextView v=t(x,28,true);v.setGravity(Gravity.CENTER);root.addView(v);}
    Button button(String x,boolean fill){Button b=new Button(this);b.setText(x);b.setAllCaps(false);b.setTextSize(16);b.setTextColor(fill?Color.WHITE:green);b.setBackgroundColor(fill?green:Color.WHITE);root.addView(b,new LinearLayout.LayoutParams(-1,62));return b;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);root.addView(e,new LinearLayout.LayoutParams(-1,62));return e;}
    void toast(String x){Toast.makeText(this,x,Toast.LENGTH_LONG).show();}
    String val(DocumentSnapshot d,String k){Object x=d.get(k);return x==null?"":String.valueOf(x);}

    void authScreen(){base();title("Best Nikah Bridge");root.addView(t("Real account • Secure Firebase Authentication • Serious Nikah only",16,false));EditText e=input("Email");e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);EditText p=input("Password (8+ characters)");p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);Button l=button("Sign in",true),c=button("Create account",false);l.setOnClickListener(v->signIn(e,p));c.setOnClickListener(v->create(e,p));}
    boolean valid(EditText e,EditText p){if(!e.getText().toString().contains("@")){e.setError("Valid email required");return false;}if(p.getText().toString().length()<8){p.setError("Minimum 8 characters");return false;}return true;}
    void signIn(EditText e,EditText p){if(!valid(e,p))return;auth.signInWithEmailAndPassword(e.getText().toString().trim(),p.getText().toString()).addOnSuccessListener(x->home()).addOnFailureListener(x->toast("Sign in failed: "+x.getMessage()));}
    void create(EditText e,EditText p){if(!valid(e,p))return;auth.createUserWithEmailAndPassword(e.getText().toString().trim(),p.getText().toString()).addOnSuccessListener(x->{Map<String,Object> m=new HashMap<>();m.put("uid",auth.getUid());m.put("profileActive",false);m.put("verificationStatus","unverified");m.put("createdAt",FieldValue.serverTimestamp());db.collection("users").document(auth.getUid()).set(m).addOnSuccessListener(y->profile());}).addOnFailureListener(x->toast("Account creation failed: "+x.getMessage()));}

    void home(){base();title("Best Nikah Bridge");root.addView(t("Halal Muslim matrimonial platform — not a dating app.",17,false));
        Button p=button("My Profile",true),r=button("Nikah Readiness Score",true),m=button("Real Recommended Matches",true),i=button("Mutual Interests & Safe Chat",true),w=button("Family / Wali Connect",true),s=button("Scam Shield & Safety",false),v=button("Real Verification",false),h=button("Nikah Assistant / Help",false),a=button("Privacy & Delete Account",false);
        p.setOnClickListener(x->profile());r.setOnClickListener(x->readiness());m.setOnClickListener(x->matches());i.setOnClickListener(x->interests());w.setOnClickListener(x->wali());s.setOnClickListener(x->safety());v.setOnClickListener(x->verification());h.setOnClickListener(x->help());a.setOnClickListener(x->account());root.addView(t("Signed in: "+auth.getCurrentUser().getEmail(),14,false));}

    void profile(){base();title("My Real Nikah Profile");EditText name=input("Full name"),age=input("Age (18+)"),country=input("Country"),city=input("City"),gender=input("Gender"),marital=input("Marital status"),intent=input("Marriage intention"),practice=input("Religious practice"),about=input("About yourself and family values"),pref=input("Partner preferences"),timeline=input("Marriage timeline"),family=input("Family/Wali preference"),deal=input("Deal-breakers / non-negotiables");Button save=button("Save Profile",true),ver=button("Request Verification",false),back=button("Back",false);
        db.collection("users").document(auth.getUid()).get().addOnSuccessListener(d->{name.setText(val(d,"name"));age.setText(val(d,"age"));country.setText(val(d,"country"));city.setText(val(d,"city"));gender.setText(val(d,"gender"));marital.setText(val(d,"maritalStatus"));intent.setText(val(d,"marriageIntent"));practice.setText(val(d,"religiousPractice"));about.setText(val(d,"about"));pref.setText(val(d,"partnerPreference"));timeline.setText(val(d,"marriageTimeline"));family.setText(val(d,"familyInvolvement"));deal.setText(val(d,"dealbreakers"));});
        save.setOnClickListener(x->{int n;try{n=Integer.parseInt(age.getText().toString().trim());}catch(Exception e){age.setError("Enter age");return;}if(n<18||n>100){age.setError("Age must be 18-100");return;}if(name.getText().toString().trim().length()<2||about.getText().toString().trim().length()<30||pref.getText().toString().trim().length()<10){toast("Complete name, About and partner preferences.");return;}Map<String,Object> q=new HashMap<>();q.put("uid",auth.getUid());q.put("name",name.getText().toString().trim());q.put("age",n);q.put("country",country.getText().toString().trim());q.put("city",city.getText().toString().trim());q.put("gender",gender.getText().toString().trim());q.put("maritalStatus",marital.getText().toString().trim());q.put("marriageIntent",intent.getText().toString().trim());q.put("religiousPractice",practice.getText().toString().trim());q.put("about",about.getText().toString().trim());q.put("partnerPreference",pref.getText().toString().trim());q.put("marriageTimeline",timeline.getText().toString().trim());q.put("familyInvolvement",family.getText().toString().trim());q.put("dealbreakers",deal.getText().toString().trim());q.put("profileActive",true);q.put("updatedAt",FieldValue.serverTimestamp());db.collection("users").document(auth.getUid()).update(q).addOnSuccessListener(y->{toast("Profile saved securely.");home();}).addOnFailureListener(y->toast("Save failed: "+y.getMessage()));});
        ver.setOnClickListener(x->verification());back.setOnClickListener(x->home());}

    void readiness(){base();title("Nikah Readiness Score");root.addView(t("Transparent preparation score — not a religious ruling or compatibility guarantee.",15,false));db.collection("users").document(auth.getUid()).get().addOnSuccessListener(d->{int z=0;String[] keys={"name","country","city","about","partnerPreference","marriageIntent","marriageTimeline","familyInvolvement","dealbreakers"};for(String k:keys)if(!val(d,k).trim().isEmpty())z+=10;if(d.getLong("age")!=null)z+=10;if("verified".equalsIgnoreCase(val(d,"verificationStatus")))z+=10;if(z>100)z=100;root.addView(t("Readiness Score: "+z+" / 100",26,true));root.addView(t(z>=80?"Strong preparation. Continue respectful family discussions.":z>=60?"Good foundation. Complete missing areas.":"Clarify your goals and complete your profile first.",17,false));});Button b=button("Back",false);b.setOnClickListener(x->home());}

    void matches(){base();title("Real Recommended Matches");root.addView(t("Only active Firebase profiles. No fake/demo members.",15,false));db.collection("users").whereEqualTo("profileActive",true).limit(50).get().addOnSuccessListener(q->{boolean any=false;for(DocumentSnapshot d:q){if(auth.getUid().equals(d.getId()))continue;any=true;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);root.addView(c);c.addView(t(val(d,"name")+" • "+val(d,"age"),20,true));c.addView(t(val(d,"city")+(val(d,"country").isEmpty()?"":", "+val(d,"country"))+"\n"+val(d,"marriageIntent")+"\nVerification: "+val(d,"verificationStatus"),15,false));c.addView(t("Why we matched: serious marriage intent • family values • preferences/timeline",15,false));Button b=button("Express Interest",true);c.addView(b);b.setOnClickListener(x->sendInterest(d.getId(),b));}if(!any)root.addView(t("No real profiles are available yet.",16,false));}).addOnFailureListener(x->toast("Matches failed: "+x.getMessage()));Button b=button("Back",false);b.setOnClickListener(x->home());}
    void sendInterest(String uid,Button b){Map<String,Object> m=new HashMap<>();m.put("fromUid",auth.getUid());m.put("toUid",uid);m.put("status","pending");m.put("createdAt",FieldValue.serverTimestamp());db.collection("interests").add(m).addOnSuccessListener(x->{b.setEnabled(false);b.setText("Interest Sent ✓");toast("Interest sent. Chat stays locked until mutual acceptance.");}).addOnFailureListener(x->toast("Interest failed: "+x.getMessage()));}

    void interests(){base();title("Mutual Interests & Safe Chat");root.addView(t("Mutual-only communication. Server rules control access.",15,false));String me=auth.getUid();root.addView(t("Incoming",19,true));db.collection("interests").whereEqualTo("toUid",me).whereEqualTo("status","pending").get().addOnSuccessListener(q->{for(DocumentSnapshot d:q){String id=d.getId(),from=val(d,"fromUid");Button a=button("Accept interest • "+from,true);Button r=button("Decline • "+from,false);a.setOnClickListener(x->accept(id,from));r.setOnClickListener(x->db.collection("interests").document(id).update("status","declined").addOnSuccessListener(y->interests()));}});root.addView(t("Active connections",19,true));db.collection("connections").whereEqualTo("uid1",me).whereEqualTo("status","active").get().addOnSuccessListener(q->connectionButtons(q));db.collection("connections").whereEqualTo("uid2",me).whereEqualTo("status","active").get().addOnSuccessListener(q->connectionButtons(q));Button b=button("Back",false);b.setOnClickListener(x->home());}
    void accept(String id,String from){db.collection("interests").document(id).update("status","accepted").addOnSuccessListener(x->{Map<String,Object> m=new HashMap<>();m.put("otherUid",from);fn.getHttpsCallable("createMutualConnection").call(m).addOnSuccessListener(y->{toast("Mutual connection created. Safe Chat unlocked.");interests();}).addOnFailureListener(y->{toast("Accepted. Waiting for the other side to accept.");interests();});});}
    void connectionButtons(QuerySnapshot q){for(DocumentSnapshot d:q){String other=auth.getUid().equals(val(d,"uid1"))?val(d,"uid2"):val(d,"uid1");Button b=button("Safe Chat • "+other,true);b.setOnClickListener(x->chat(d.getId(),other));}}

    void chat(String cid,String other){base();title("Safe Chat");root.addView(t("Mutual connection only. Never send money, OTPs or passwords.",15,false));LinearLayout msgs=new LinearLayout(this);msgs.setOrientation(LinearLayout.VERTICAL);root.addView(msgs);EditText e=input("Respectful message");Button send=button("Send",true),report=button("Report / Block",false),back=button("Back",false);db.collection("connections").document(cid).collection("messages").orderBy("sentAt",Query.Direction.ASCENDING).limitToLast(100).get().addOnSuccessListener(q->{for(DocumentSnapshot d:q)msgs.addView(t((auth.getUid().equals(val(d,"fromUid"))?"You: ":"Them: ")+val(d,"text"),15,false));});send.setOnClickListener(x->{String text=e.getText().toString().trim();if(text.isEmpty())return;Map<String,Object> m=new HashMap<>();m.put("fromUid",auth.getUid());m.put("toUid",other);m.put("text",text);m.put("sentAt",FieldValue.serverTimestamp());db.collection("connections").document(cid).collection("messages").add(m).addOnSuccessListener(y->{e.setText("");msgs.addView(t("You: "+text,15,false));}).addOnFailureListener(y->toast("Message blocked by secure rules."));});report.setOnClickListener(x->report(other));back.setOnClickListener(x->interests());}
    void report(String uid){Map<String,Object> m=new HashMap<>();m.put("reporterUid",auth.getUid());m.put("reportedUid",uid);m.put("reason","Safety concern");m.put("status","pending");m.put("createdAt",FieldValue.serverTimestamp());db.collection("reports").add(m).addOnSuccessListener(x->toast("Report sent to moderation."));}

    void wali(){base();title("Family / Wali Connect");root.addView(t("Optional and consent-based. Trusted Wali participation is handled by the secure backend.",15,false));EditText e=input("Wali Firebase UID (if they have an account)");Button b=button("Request Wali Connection",true),back=button("Back",false);b.setOnClickListener(x->{Map<String,Object> m=new HashMap<>();m.put("waliUid",e.getText().toString().trim());fn.getHttpsCallable("requestWaliConnection").call(m).addOnSuccessListener(y->toast("Wali request sent.")).addOnFailureListener(y->toast("Wali request failed: "+y.getMessage()));});back.setOnClickListener(x->home());}
    void safety(){base();title("Scam Shield & Safety");root.addView(t("• Never send money.\n• Never share OTP/passwords.\n• Keep contact details private.\n• Verification is not a guarantee.\n• Report suspicious behavior.\n• Involve family/Wali when appropriate.\n• For threats/emergencies contact local authorities.",17,false));Button b=button("Back",false);b.setOnClickListener(x->home());}
    void verification(){base();title("Real Verification");root.addView(t("Requests are stored in Firebase. Only an authorized admin/backend may mark a member verified.",15,false));EditText note=input("Verification note (never enter sensitive ID numbers here)");Button b=button("Submit Verification Request",true),back=button("Back",false);db.collection("users").document(auth.getUid()).get().addOnSuccessListener(d->root.addView(t("Current status: "+val(d,"verificationStatus"),18,true)));b.setOnClickListener(x->{Map<String,Object> m=new HashMap<>();m.put("userUid",auth.getUid());m.put("note",note.getText().toString().trim());m.put("status","pending");m.put("createdAt",FieldValue.serverTimestamp());db.collection("verifications").add(m).addOnSuccessListener(y->toast("Verification request submitted."));});back.setOnClickListener(x->home());}
    void help(){base();title("Nikah Assistant / Help");root.addView(t("Get help preparing respectful questions about compatibility, family involvement, marriage timeline, boundaries and safety. For religious rulings, consult a qualified scholar.",17,false));Button b=button("Back",false);b.setOnClickListener(x->home());}
    void account(){base();title("Privacy & Account");root.addView(t("Your account uses real Firebase Authentication. Deletion is performed by the trusted backend function.",16,false));Button d=button("Permanently Delete Account",true),out=button("Sign out",false),b=button("Back",false);d.setOnClickListener(x->deleteAccount());out.setOnClickListener(x->{auth.signOut();authScreen();});b.setOnClickListener(x->home());}
    void deleteAccount(){fn.getHttpsCallable("deleteMyAccount").call(new HashMap<>()).addOnSuccessListener(x->{auth.signOut();toast("Account deleted.");authScreen();}).addOnFailureListener(x->toast("Deletion failed: "+x.getMessage()));}
}
