package com.nikahbridge;

import android.app.Activity;import android.app.AlertDialog;import android.graphics.Color;import android.graphics.Typeface;import android.os.Bundle;import android.widget.*;

public class AccountDeletionActivity extends Activity{
 LinearLayout root;final int green=Color.rgb(18,103,82),dark=Color.rgb(30,45,41),gray=Color.rgb(95,108,103),red=Color.rgb(165,50,50);
 public void onCreate(Bundle b){super.onCreate(b);render();}
 TextView txt(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(bold?dark:gray);t.setPadding(6,8,6,12);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);return b;}
 void render(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,24,22,32);sc.addView(root);setContentView(sc);TextView h=txt("Account & Privacy",28,true);root.addView(h);root.addView(txt("Permanent deletion removes your Azure profile, matches, messages, family links, verification records and stored photos handled by the Azure backend.",16,false));Button del=btn("Permanently Delete Account");root.addView(del,new LinearLayout.LayoutParams(-1,70));Button out=btn("Sign out");root.addView(out,new LinearLayout.LayoutParams(-1,70));Button back=btn("Back");root.addView(back,new LinearLayout.LayoutParams(-1,70));status("Ready");del.setOnClickListener(v->confirmDelete());out.setOnClickListener(v->{com.google.firebase.auth.FirebaseAuth.getInstance().signOut();finish();});back.setOnClickListener(v->finish());}
 void status(String s){root.addView(txt("Status: "+s,15,false));}
 void confirmDelete(){new AlertDialog.Builder(this).setTitle("Permanent deletion").setMessage("This permanently deletes your Azure account data. Continue?").setNegativeButton("Cancel",null).setPositiveButton("DELETE", (d,w)->{AzureApiClient.delete("/account",null,new AzureApiClient.Callback(){public void ok(int c,String s){runOnUiThread(()->{Toast.makeText(AccountDeletionActivity.this,"Account deleted permanently.",Toast.LENGTH_LONG).show();com.google.firebase.auth.FirebaseAuth.getInstance().signOut();finish();});}public void err(String e){runOnUiThread(()->Toast.makeText(AccountDeletionActivity.this,"Azure deletion failed. Nothing was confirmed.",Toast.LENGTH_LONG).show());}});}).show();}
}