package com.nikahbridge;

import android.app.Activity;import android.os.Bundle;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.widget.*;import org.json.JSONObject;

public class FamilyBridge2Activity extends Activity{
 LinearLayout root;EditText name,email,phone,linkId;TextView status;final int green=Color.rgb(18,103,82),dark=Color.rgb(30,45,41),gray=Color.rgb(85,100,95);
 public void onCreate(Bundle b){super.onCreate(b);render();load();}
 TextView txt(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(bold?dark:gray);t.setPadding(6,8,6,10);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 Button btn(String s,boolean fill){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(fill?Color.WHITE:green);GradientDrawable g=new GradientDrawable();g.setColor(fill?green:Color.WHITE);g.setCornerRadius(18);if(!fill)g.setStroke(2,green);b.setBackground(g);root.addView(b,new LinearLayout.LayoutParams(-1,62));return b;}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);root.addView(e,new LinearLayout.LayoutParams(-1,62));return e;}
 void render(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,22,20,30);s.addView(root);setContentView(s);root.addView(txt("Family / Wali Connect",27,true));root.addView(txt("Real Azure family-link service. The Wali must use a matching verified email or phone; no Firebase UID is requested.",15,false));name=input("Wali name");email=input("Wali email");phone=input("Wali phone (E.164)");Button req=btn("Request Wali Connection",true);req.setOnClickListener(v->create());linkId=input("Family link ID");Button verify=btn("Verify Wali Connection",false);verify.setOnClickListener(v->verify());Button revoke=btn("Revoke Connection",false);revoke.setOnClickListener(v->revoke());status=txt("Status: loading…",15,false);root.addView(status);Button back=btn("Back",false);back.setOnClickListener(v->finish());}
 void load(){AzureApiClient.get("/family-links",new AzureApiClient.Callback(){public void ok(int c,String s){runOnUiThread(()->status.setText("Status: Azure family links loaded"));}public void err(String e){runOnUiThread(()->status.setText("Status: Azure family links unavailable"));}});}
 void create(){try{JSONObject b=new JSONObject().put("waliName",name.getText().toString().trim()).put("waliEmail",email.getText().toString().trim()).put("waliPhoneE164",phone.getText().toString().trim());AzureApiClient.post("/family-links",b.toString(),cb("Wali connection request stored in Azure."));}catch(Exception e){status.setText("Status: request error");}}
 void verify(){AzureApiClient.post("/family-links/"+linkId.getText().toString().trim()+"/verify","{}",cb("Wali connection verified in Azure."));}
 void revoke(){AzureApiClient.delete("/family-links/"+linkId.getText().toString().trim(),"{}",cb("Wali connection revoked in Azure."));}
 AzureApiClient.Callback cb(String ok){return new AzureApiClient.Callback(){public void ok(int c,String s){runOnUiThread(()->status.setText(ok));}public void err(String e){runOnUiThread(()->status.setText("Status: Azure action failed"));}};}
}