package com.nikahbridge;

import android.app.Activity; import android.os.Bundle; import android.graphics.Color; import android.graphics.Typeface; import android.view.Gravity; import android.content.Intent; import android.widget.*; import com.google.firebase.auth.FirebaseAuth; import com.google.firebase.functions.FirebaseFunctions; import java.util.*;

/** Real identity verification status/submission entry point. Document upload must target the private verificationDocuments path. */
public class IdentityVerificationActivity extends Activity {
  FirebaseAuth auth; FirebaseFunctions functions; LinearLayout root; TextView status; EditText path; Spinner type;
  int green=Color.rgb(18,103,82), dark=Color.rgb(30,45,41);
  public void onCreate(Bundle b){super.onCreate(b);auth=FirebaseAuth.getInstance();functions=FirebaseFunctions.getInstance();build();load();}
  TextView t(String s,int z,boolean bold){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(bold?dark:Color.rgb(85,100,95));x.setPadding(8,10,8,10);if(bold)x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return x;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
  void build(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,22,20,28);sc.addView(root);setContentView(sc);TextView h=t("Identity Verification",27,true);h.setGravity(Gravity.CENTER);root.addView(h);root.addView(t("Use a real government identity document. Your document is private and is reviewed before a verified status is granted.",15,false));root.addView(t("Document type",16,true));type=new Spinner(this);String[] a={"national_id","passport","driving_license"};type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));root.addView(type);root.addView(t("Private Firebase Storage path",16,true));path=new EditText(this);path.setHint("verificationDocuments/your-uid/document.jpg");root.addView(path,new LinearLayout.LayoutParams(-1,65));Button submit=btn("Submit Real Verification");submit.setOnClickListener(v->submit());root.addView(submit);Button refresh=btn("Refresh Status");refresh.setOnClickListener(v->load());root.addView(refresh);Button open=btn("Open Verified Feature Hub");open.setOnClickListener(v->openIfVerified());root.addView(open);Button back=btn("Back");back.setOnClickListener(v->finish());root.addView(back);status=t("Status: loading…",15,false);root.addView(status);}
  void load(){if(auth.getCurrentUser()==null){status.setText("Status: sign in required");return;}functions.getHttpsCallable("getMyVerificationStatus").call(new HashMap<>()).addOnSuccessListener(r->{Object d=r.getData();status.setText("Status: "+String.valueOf(d));}).addOnFailureListener(e->status.setText("Status: could not load verification status"));}
  void submit(){if(auth.getCurrentUser()==null){status.setText("Status: sign in required");return;}String p=path.getText().toString().trim();Map<String,Object>d=new HashMap<>();d.put("documentType",String.valueOf(type.getSelectedItem()));d.put("storagePath",p);status.setText("Status: submitting real verification…");functions.getHttpsCallable("submitIdentityVerification").call(d).addOnSuccessListener(r->{status.setText("Status: verification submitted — pending review");}).addOnFailureListener(e->status.setText("Status: submission failed — "+(e.getMessage()==null?"try again":e.getMessage())));}
  void openIfVerified(){if(auth.getCurrentUser()==null){status.setText("Status: sign in required");return;}functions.getHttpsCallable("getMyVerificationStatus").call(new HashMap<>()).addOnSuccessListener(r->{String s=String.valueOf(r.getData()).toLowerCase(Locale.US);if(s.contains("verified")||s.contains("approved")){startActivity(new Intent(this,PostVerificationFeatureHubActivity.class));}else{status.setText("Status: verification is not approved yet. The verified feature hub remains locked.");}}).addOnFailureListener(e->status.setText("Status: could not verify your current status."));}
}
