package com.nikahbridge;

import android.app.Activity;import android.content.Intent;import android.net.Uri;import android.os.Bundle;import android.graphics.Color;import android.graphics.Typeface;import android.view.Gravity;import android.widget.*;import java.io.ByteArrayOutputStream;import java.io.InputStream;import java.util.Locale;

public class IdentityVerificationActivity extends Activity{
 LinearLayout root;Spinner type;TextView status,fileLabel;Uri selected;final int green=Color.rgb(18,103,82),dark=Color.rgb(30,45,41),gray=Color.rgb(85,100,95);
 public void onCreate(Bundle b){super.onCreate(b);build();load();}
 TextView t(String s,int z,boolean bold){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(bold?dark:gray);x.setPadding(8,10,8,10);if(bold)x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return x;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 void build(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,22,20,28);sc.addView(root);setContentView(sc);TextView h=t("Real Verification",27,true);h.setGravity(Gravity.CENTER);root.addView(h);root.addView(t("Your document is uploaded directly to private Azure Storage and the verification record is stored in Azure PostgreSQL for authorized review.",15,false));type=new Spinner(this);type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"identity","manual"}));root.addView(type);Button pick=btn("Choose Private ID Document");root.addView(pick);fileLabel=t("No document selected",14,false);root.addView(fileLabel);pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/jpeg","image/png","application/pdf"});i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,41);});Button submit=btn("Submit Real Verification");root.addView(submit);submit.setOnClickListener(v->submit());Button refresh=btn("Refresh Status");root.addView(refresh);refresh.setOnClickListener(v->load());Button back=btn("Back");root.addView(back);back.setOnClickListener(v->finish());status=t("Status: loading…",15,false);root.addView(status);}
 protected void onActivityResult(int r,int code,Intent data){super.onActivityResult(r,code,data);if(r==41&&code==RESULT_OK&&data!=null){selected=data.getData();fileLabel.setText(selected==null?"No document selected":"Document selected securely");}}
 void load(){AzureApiClient.get("/verification",new AzureApiClient.Callback(){public void ok(int c,String s){runOnUiThread(()->status.setText("Status: Azure verification status loaded"));}public void err(String e){runOnUiThread(()->status.setText("Status: Azure verification status unavailable"));}});}
 void submit(){if(selected==null){status.setText("Status: choose a document first");return;}try{InputStream in=getContentResolver().openInputStream(selected);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n,total=0;while((n=in.read(b))>0){total+=n;if(total>8*1024*1024)throw new Exception("Document too large");out.write(b,0,n);}in.close();String mime=getContentResolver().getType(selected);if(mime==null)mime="application/octet-stream";String name="verification-"+System.currentTimeMillis();String ext=mime.equals("application/pdf")?".pdf":mime.equals("image/png")?".png":".jpg";status.setText("Status: uploading securely to Azure…");AzureApiClient.multipart("/verification/identity","document",name+ext,mime,out.toByteArray(),new String[]{"documentType"},new String[]{String.valueOf(type.getSelectedItem())},new AzureApiClient.Callback(){public void ok(int c,String s){runOnUiThread(()->status.setText("Status: verification submitted to Azure — pending authorized review"));}public void err(String e){runOnUiThread(()->status.setText("Status: Azure verification submission failed"));}});}catch(Exception e){status.setText("Status: document could not be prepared");}}
}