package com.nikahbridge;

import android.app.Activity;
import android.app.AlertDialog;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.widget.*;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;
import com.google.firebase.firestore.QuerySnapshot;
import com.google.firebase.firestore.SetOptions;
import com.google.firebase.functions.FirebaseFunctions;
import com.google.firebase.ai.FirebaseAI;
import com.google.firebase.ai.GenerativeBackend;
import com.google.firebase.ai.GenerativeModel;
import com.google.firebase.ai.GenerativeModelFutures;
import com.google.firebase.ai.type.Content;
import com.google.firebase.ai.type.GenerateContentResponse;
import com.google.common.util.concurrent.ListenableFuture;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** Best Nikah Bridge production entry point. Real Firebase data only. */
public class MainActivity extends Activity {
    private FirebaseAuth auth;
    private FirebaseFirestore db;
    private FirebaseFunctions functions;
    private LinearLayout root;
    private ExecutorService aiExecutor;
    private final int green=Color.rgb(18,103,82), dark=Color.rgb(30,45,41), gray=Color.rgb(95,108,103), red=Color.rgb(165,50,50), light=Color.rgb(247,250,249);

    @Override protected void onCreate(Bundle state){
        super.onCreate(state); auth=FirebaseAuth.getInstance(); db=FirebaseFirestore.getInstance(); functions=FirebaseFunctions.getInstance(); aiExecutor=Executors.newSingleThreadExecutor(); route();
    }
    @Override protected void onDestroy(){ if(aiExecutor!=null) aiExecutor.shutdownNow(); super.onDestroy(); }
    @Override public void onBackPressed(){ if(auth.getCurrentUser()==null) authScreen(); else home(); }

    private void route(){
        FirebaseUser u=auth.getCurrentUser(); if(u==null){authScreen();return;}
        u.reload().addOnSuccessListener(x->{
            if(!u.isEmailVerified()){verificationGate();return;}
            db.collection("users").document(u.getUid()).get().addOnSuccessListener(d->{if(!d.exists()||!Boolean.TRUE.equals(d.getBoolean("profileActive")))profile();else home();}).addOnFailureListener(e->toast("Secure profile check failed. Please try again."));
        }).addOnFailureListener(e->toast("Secure account check failed. Please sign in again."));
    }
    private void base(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(light);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,24,22,32);s.addView(root);setContentView(s);}
    private TextView text(String v,int size,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(size);t.setTextColor(bold?dark:gray);t.setPadding(6,8,6,12);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private void title(String v){TextView t=text(v,28,true);t.setGravity(Gravity.CENTER);root.addView(t);}
    private Button button(String label,boolean filled){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(16);b.setTextColor(filled?Color.WHITE:green);GradientDrawable g=new GradientDrawable();g.setColor(filled?green:Color.WHITE);g.setCornerRadius(18);if(!filled)g.setStroke(2,green);b.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,62);p.setMargins(0,6,0,6);root.addView(b,p);return b;}
    private Button danger(String label){Button b=button(label,false);b.setTextColor(red);GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(18);g.setStroke(2,red);b.setBackground(g);return b;}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setPadding(14,8,14,8);root.addView(e,new LinearLayout.LayoutParams(-1,62));return e;}
    private void section(String v){root.addView(text(v,19,true));}
    private void toast(String v){Toast.makeText(this,v,Toast.LENGTH_LONG).show();}
    private String val(DocumentSnapshot d,String key){Object v=d.get(key);return v==null?"":String.valueOf(v);}
    private boolean signedIn(){return auth.getCurrentUser()!=null;}
    private int intVal(DocumentSnapshot d,String key,int fallback){Long x=d.getLong(key);return x==null?fallback:x.intValue();}

    private void authScreen(){
        base();title("Best Nikah Bridge");root.addView(text("Real Firebase account • Serious Nikah only • Not a dating app",16,false));
        EditText email=input("Email address");email.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);EditText password=input("Password (minimum 8 characters)");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
        Button sign=button("Sign in",true),create=button("Create account",false),forgot=button("Forgot password",false),terms=button("Terms & Community Rules",false);
        sign.setOnClickListener(v->{if(!valid(email,password))return;auth.signInWithEmailAndPassword(email.getText().toString().trim(),password.getText().toString()).addOnSuccessListener(x->route()).addOnFailureListener(e->toast("Sign in failed. Check your email and password."));});
        create.setOnClickListener(v->{if(!valid(email,password))return;auth.createUserWithEmailAndPassword(email.getText().toString().trim(),password.getText().toString()).addOnSuccessListener(x->{FirebaseUser u=x.getUser();if(u==null)return;u.sendEmailVerification();Map<String,Object> p=new HashMap<>();p.put("uid",u.getUid());p.put("profileActive",false);p.put("discoverable",false);p.put("verificationStatus","unverified");p.put("termsAccepted",false);p.put("intentConfirmed",false);p.put("createdAt",FieldValue.serverTimestamp());db.collection("users").document(u.getUid()).set(p).addOnSuccessListener(y->verificationGate()).addOnFailureListener(e->toast("Account setup failed."));}).addOnFailureListener(e->toast("Account creation failed. Email may already be registered."));});
        forgot.setOnClickListener(v->{String e=email.getText().toString().trim();if(!e.contains("@")){email.setError("Enter your email first");return;}auth.sendPasswordResetEmail(e).addOnSuccessListener(x->toast("Password reset email sent.")).addOnFailureListener(x->toast("Could not send password reset email."));});terms.setOnClickListener(v->terms());
    }
    private boolean valid(EditText e,EditText p){if(!e.getText().toString().trim().contains("@")){e.setError("Valid email required");return false;}if(p.getText().toString().length()<8){p.setError("Minimum 8 characters");return false;}return true;}
    private void verificationGate(){base();title("Verify your email");root.addView(text("Email verification is required before your profile can become active.",16,false));Button resend=button("Resend verification email",true),refresh=button("I verified — continue",false),out=button("Sign out",false);resend.setOnClickListener(v->{FirebaseUser u=auth.getCurrentUser();if(u!=null)u.sendEmailVerification().addOnSuccessListener(x->toast("Verification email sent."));});refresh.setOnClickListener(v->{FirebaseUser u=auth.getCurrentUser();if(u==null){authScreen();return;}u.reload().addOnSuccessListener(x->{if(u.isEmailVerified())route();else toast("Email is not verified yet.");});});out.setOnClickListener(v->{auth.signOut();authScreen();});}

    private void home(){
        base();title("Best Nikah Bridge");root.addView(text("A serious Muslim marriage platform built around trust, compatibility, family and safe Nikah — not dating.",17,false));
        Button p=button("My Profile & Intent",true),r=button("Nikah Readiness Score",true),m=button("Compatibility Matches",true),i=button("Mutual Interests & Safe Chat",true),c=button("🌍 Global Community Chat — FREE",true),w=button("Family / Wali Connect",true),s=button("Scam Shield & Safety",false),v=button("Real Verification",false),h=button("AI Nikah Assistant",false),pr=button("Privacy Control Center",false),a=button("Delete Account / Sign out",false);
        p.setOnClickListener(x->profile());r.setOnClickListener(x->readiness());m.setOnClickListener(x->matches());i.setOnClickListener(x->interests());c.setOnClickListener(x->communityChat());w.setOnClickListener(x->wali());s.setOnClickListener(x->safety());v.setOnClickListener(x->verification());h.setOnClickListener(x->help());pr.setOnClickListener(x->privacy());a.setOnClickListener(x->account());
        root.addView(text("Real Firebase data only. No demo members, fake match records or fake verification badges.",14,false));
    }

    private void profile(){
        base();title("My Real Nikah Profile");root.addView(text("Complete this honestly. Your profile becomes discoverable only after email verification, Terms acceptance and all required matching fields.",15,false));
        EditText name=input("Full name"),age=input("Age (18+)"),minAge=input("Preferred partner minimum age (18+)"),maxAge=input("Preferred partner maximum age (18+)"),country=input("Country"),city=input("City"),gender=input("Gender"),looking=input("Looking for (gender / preference)"),marital=input("Marital status"),intent=input("Marriage intention"),practice=input("Religious practice"),about=input("About yourself and family values (30+ characters)"),pref=input("Partner preferences: location, values, education, lifestyle, etc."),timeline=input("Marriage timeline"),family=input("Family / Wali involvement preference"),deal=input("Compatibility deal-breakers / non-negotiables (5+ characters)");
        CheckBox accepted=new CheckBox(this);accepted.setText("I accept the Terms & Community Rules and confirm this is a genuine marriage intention.");root.addView(accepted);Button save=button("Save & Activate Profile",true),verify=button("Request Verification",false),back=button("Back",false);
        db.collection("users").document(auth.getUid()).get().addOnSuccessListener(d->{name.setText(val(d,"name"));age.setText(val(d,"age"));minAge.setText(val(d,"preferredMinAge"));maxAge.setText(val(d,"preferredMaxAge"));country.setText(val(d,"country"));city.setText(val(d,"city"));gender.setText(val(d,"gender"));looking.setText(val(d,"lookingFor"));marital.setText(val(d,"maritalStatus"));intent.setText(val(d,"marriageIntent"));practice.setText(val(d,"religiousPractice"));about.setText(val(d,"about"));pref.setText(val(d,"partnerPreference"));timeline.setText(val(d,"marriageTimeline"));family.setText(val(d,"familyInvolvement"));deal.setText(val(d,"dealbreakers"));accepted.setChecked(Boolean.TRUE.equals(d.getBoolean("termsAccepted")));root.addView(text("Verification status: "+val(d,"verificationStatus"),15,false));});
        save.setOnClickListener(v->{int a,lo,hi;try{a=Integer.parseInt(age.getText().toString().trim());lo=Integer.parseInt(minAge.getText().toString().trim());hi=Integer.parseInt(maxAge.getText().toString().trim());}catch(Exception e){toast("Age fields must contain numbers.");return;}if(a<18||a>100){age.setError("Age must be 18–100");return;}if(lo<18||hi>100||lo>hi){toast("Partner age range must be valid.");return;}String n=name.getText().toString().trim(),c=country.getText().toString().trim(),ci=city.getText().toString().trim(),g=gender.getText().toString().trim(),lf=looking.getText().toString().trim(),ms=marital.getText().toString().trim(),in=intent.getText().toString().trim(),rp=practice.getText().toString().trim(),ab=about.getText().toString().trim(),pp=pref.getText().toString().trim(),tl=timeline.getText().toString().trim(),fa=family.getText().toString().trim(),dbk=deal.getText().toString().trim();if(n.length()<2||c.isEmpty()||ci.isEmpty()||g.isEmpty()||lf.isEmpty()||ms.isEmpty()||in.isEmpty()||rp.isEmpty()||ab.length()<30||pp.length()<10||tl.isEmpty()||fa.isEmpty()||dbk.length()<5){toast("Complete every required profile and matching field.");return;}if(!accepted.isChecked()){toast("Accept the Terms and confirm genuine marriage intention first.");return;}FirebaseUser u=auth.getCurrentUser();if(u==null||!u.isEmailVerified()){toast("Verify your email first.");return;}Map<String,Object> q=new HashMap<>();q.put("uid",u.getUid());q.put("name",n);q.put("age",a);q.put("preferredMinAge",lo);q.put("preferredMaxAge",hi);q.put("country",c);q.put("city",ci);q.put("gender",g);q.put("lookingFor",lf);q.put("maritalStatus",ms);q.put("marriageIntent",in);q.put("religiousPractice",rp);q.put("about",ab);q.put("partnerPreference",pp);q.put("marriageTimeline",tl);q.put("familyInvolvement",fa);q.put("dealbreakers",dbk);q.put("termsAccepted",true);q.put("intentConfirmed",true);q.put("profileActive",true);q.put("discoverable",true);q.put("updatedAt",FieldValue.serverTimestamp());db.collection("users").document(u.getUid()).set(q,SetOptions.merge()).addOnSuccessListener(x->{toast("Real profile activated securely.");home();}).addOnFailureListener(e->toast("Profile could not be saved. Check your connection."));});
        verify.setOnClickListener(v->verification());back.setOnClickListener(v->home());
    }

    private void readiness(){base();title("Nikah Readiness Score");root.addView(text("A transparent preparation aid — not a religious ruling and never a guarantee of compatibility.",15,false));db.collection("users").document(auth.getUid()).get().addOnSuccessListener(d->{int score=0;String[] keys={"name","country","city","gender","lookingFor","maritalStatus","about","partnerPreference","marriageIntent","marriageTimeline","familyInvolvement","dealbreakers"};for(String k:keys)if(!val(d,k).trim().isEmpty())score+=6;if(d.getLong("age")!=null)score+=6;if(d.getLong("preferredMinAge")!=null&&d.getLong("preferredMaxAge")!=null)score+=6;if(Boolean.TRUE.equals(d.getBoolean("termsAccepted")))score+=4;if(Boolean.TRUE.equals(d.getBoolean("intentConfirmed")))score+=4;if("verified".equalsIgnoreCase(val(d,"verificationStatus")))score+=8;if(score>100)score=100;root.addView(text("Nikah Readiness: "+score+" / 100",27,true));root.addView(text(score>=85?"Strong preparation. Focus on family discussion and real-world compatibility.":score>=65?"Good foundation. Complete the remaining areas before moving quickly.":"Build your profile, boundaries, timeline and family involvement first.",17,false));});Button b=button("Back",false);b.setOnClickListener(v->home());}

    private void matches(){base();title("Compatibility Matches");root.addView(text("Real profiles only. We score reciprocal age/gender preferences, intent, timeline, location, values, deal-breakers and trust signals. A score is a guide, not a promise.",15,false));db.collection("users").document(auth.getUid()).get().addOnSuccessListener(me->{if(!Boolean.TRUE.equals(me.getBoolean("profileActive"))){toast("Complete your profile first.");profile();return;}loadBlocked(blocked->{db.collection("users").whereEqualTo("profileActive",true).whereEqualTo("discoverable",true).limit(100).get().addOnSuccessListener(q->{ArrayList<Match> list=new ArrayList<>();for(DocumentSnapshot d:q){if(auth.getUid().equals(d.getId())||blocked.contains(d.getId()))continue;int sc=score(me,d);if(sc>=45)list.add(new Match(d,sc));}list.sort((a,b)->Integer.compare(b.score,a.score));if(list.isEmpty())root.addView(text("No strong real matches are available yet. Keep your profile complete and check again as the community grows.",16,false));for(Match x:list)addMatch(me,x.doc,x.score);}).addOnFailureListener(e->toast("Could not load real matches."));});}).addOnFailureListener(e->toast("Could not load your profile."));Button b=button("Back",false);b.setOnClickListener(v->home());}
    private static class Match{DocumentSnapshot doc;int score;Match(DocumentSnapshot d,int s){doc=d;score=s;}}
    private void loadBlocked(final BlockCallback cb){Set<String> out=new HashSet<>();db.collection("blocks").whereEqualTo("blockerUid",auth.getUid()).get().addOnSuccessListener(a->{for(DocumentSnapshot d:a)out.add(val(d,"blockedUid"));db.collection("blocks").whereEqualTo("blockedUid",auth.getUid()).get().addOnSuccessListener(b->{for(DocumentSnapshot d:b)out.add(val(d,"blockerUid"));cb.done(out);}).addOnFailureListener(e->cb.done(out));}).addOnFailureListener(e->cb.done(out));}
    private interface BlockCallback{void done(Set<String> ids);}
    private int score(DocumentSnapshot me,DocumentSnapshot d){int s=0;int theirAge=intVal(d,"age",0),myMin=intVal(me,"preferredMinAge",0),myMax=intVal(me,"preferredMaxAge",101),theirMin=intVal(d,"preferredMinAge",0),theirMax=intVal(d,"preferredMaxAge",101),myAge=intVal(me,"age",0);if(theirAge>=myMin&&theirAge<=myMax&&myAge>=theirMin&&myAge<=theirMax)s+=25;String myLooking=val(me,"lookingFor"),theirGender=val(d,"gender"),theirLooking=val(d,"lookingFor"),myGender=val(me,"gender");if(myLooking.equalsIgnoreCase(theirGender)&&theirLooking.equalsIgnoreCase(myGender))s+=20;if(val(me,"marriageIntent").equalsIgnoreCase(val(d,"marriageIntent")))s+=10;if(val(me,"marriageTimeline").equalsIgnoreCase(val(d,"marriageTimeline")))s+=10;if(val(me,"country").equalsIgnoreCase(val(d,"country")))s+=8;if(val(me,"city").equalsIgnoreCase(val(d,"city")))s+=5;if(val(me,"religiousPractice").equalsIgnoreCase(val(d,"religiousPractice")))s+=7;if(val(me,"familyInvolvement").equalsIgnoreCase(val(d,"familyInvolvement")))s+=5;return Math.min(100,s);}
    private void addMatch(DocumentSnapshot me,DocumentSnapshot d,int score){section(val(d,"name")+" • "+intVal(d,"age",0)+" • "+score+"% compatibility");root.addView(text("Why we matched: reciprocal preferences, marriage intent, timeline, location and values.\nCountry: "+val(d,"country")+"\nCity: "+val(d,"city")+"\nIntent: "+val(d,"marriageIntent")+"\nTimeline: "+val(d,"marriageTimeline")+"\nVerification: "+val(d,"verificationStatus"),14,false));Button interest=button("Express Interest",true),safe=button("Report / Block",false);interest.setOnClickListener(v->sendInterest(d.getId()));safe.setOnClickListener(v->safetyAction(d.getId()));}
    private void sendInterest(String target){Map<String,Object> m=new HashMap<>();m.put("targetUid",target);functions.getHttpsCallable("sendInterest").call(m).addOnSuccessListener(x->toast("Interest sent. Daily limit and duplicate protection are enforced by the trusted backend.")).addOnFailureListener(e->toast("Interest was not sent: "+(e.getMessage()==null?"server rejected the request":e.getMessage())));}

    private void interests(){base();title("Mutual Interests & Safe Chat");root.addView(text("Only mutually accepted connections can use private chat. Pending interests do not reveal contact details.",15,false));db.collection("connections").whereArrayContains("members",auth.getUid()).get().addOnSuccessListener(q->{if(q.isEmpty())root.addView(text("No mutual connections yet.",16,false));for(DocumentSnapshot d:q){String other=otherUid(d);if(other.isEmpty())continue;Button b=button("Open secure chat with "+other,true);b.setOnClickListener(v->privateChat(d.getId(),other));}});Button back=button("Back",false);back.setOnClickListener(v->home());}
    private String otherUid(DocumentSnapshot d){Object members=d.get("members");if(!(members instanceof java.util.List))return "";for(Object x:(java.util.List<?>)members){String u=String.valueOf(x);if(!auth.getUid().equals(u))return u;}return "";}
    private void privateChat(String connectionId,String otherUid){base();title("Safe Private Chat");root.addView(text("Mutual connection verified. Contact details remain private. Two-message gate: you may send up to 2 messages to a person until they reply; after their reply, the conversation unlocks.",14,false));LinearLayout messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);root.addView(messages);EditText e=input("Write a respectful message...");Button send=button("Send message",true),refresh=button("Refresh",false),back=button("Back",false);Runnable load=()->db.collection("connections").document(connectionId).collection("messages").orderBy("createdAt",Query.Direction.ASCENDING).limitToLast(100).get().addOnSuccessListener(q->{messages.removeAllViews();for(DocumentSnapshot d:q)messages.addView(text((auth.getUid().equals(val(d,"senderUid"))?"You: ":"Them: ")+val(d,"text"),15,false));});send.setOnClickListener(v->{String t=e.getText().toString().trim();if(t.isEmpty()||t.length()>1000){toast("Message must be 1–1000 characters.");return;}Map<String,Object> m=new HashMap<>();m.put("connectionId",connectionId);m.put("receiverUid",otherUid);m.put("text",t);functions.getHttpsCallable("sendPrivateMessage").call(m).addOnSuccessListener(x->{e.setText("");load.run();}).addOnFailureListener(x->toast("Message blocked: "+(x.getMessage()==null?"reply gate or safety rule":x.getMessage())));});refresh.setOnClickListener(v->load.run());back.setOnClickListener(v->home());load.run();}

    private void communityChat(){base();title("🌍 Global Community Chat");root.addView(text("FREE • Members from all countries • Community conversation only. Do not post phone numbers, payment requests, OTPs or private documents. Moderation rules apply.",14,false));LinearLayout messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);root.addView(messages);EditText e=input("Write a community message...");Button send=button("Post",true),refresh=button("Refresh",false),report=button("Report community safety issue",false),back=button("Back",false);Runnable load=()->db.collection("communityMessages").orderBy("createdAt",Query.Direction.DESCENDING).limit(50).get().addOnSuccessListener(q->{messages.removeAllViews();for(DocumentSnapshot d:q)messages.addView(text(val(d,"displayName")+": "+val(d,"text"),15,false));});send.setOnClickListener(v->{String t=e.getText().toString().trim();if(t.isEmpty()||t.length()>500){toast("Message must be 1–500 characters.");return;}Map<String,Object> m=new HashMap<>();m.put("text",t);functions.getHttpsCallable("sendCommunityMessage").call(m).addOnSuccessListener(x->{e.setText("");load.run();}).addOnFailureListener(x->toast("Community post blocked by moderation/safety rules."));});refresh.setOnClickListener(v->load.run());report.setOnClickListener(v->{EditText reason=inputDialog("Describe the safety issue");new AlertDialog.Builder(this).setTitle("Community safety report").setView(reason).setPositiveButton("Send",(d,w)->{Map<String,Object> r=new HashMap<>();r.put("reporterUid",auth.getUid());r.put("reportedUid","community");r.put("reason",reason.getText().toString().trim());r.put("status","pending");r.put("createdAt",FieldValue.serverTimestamp());db.collection("reports").add(r).addOnSuccessListener(x->toast("Report sent to moderation.")).addOnFailureListener(x->toast("Report could not be sent."));}).setNegativeButton("Cancel",null).show();});back.setOnClickListener(v->home());load.run();}

    private void safetyAction(String uid){new AlertDialog.Builder(this).setTitle("Safety action").setItems(new String[]{"Report user","Block user","Cancel"},(d,w)->{if(w==0)report(uid);else if(w==1)block(uid);}).show();}
    private void report(String uid){final EditText e=inputDialog("Reason for report");new AlertDialog.Builder(this).setTitle("Report user").setView(e).setPositiveButton("Send report",(d,w)->{String reason=e.getText().toString().trim();if(reason.isEmpty())reason="Safety concern";Map<String,Object> m=new HashMap<>();m.put("reporterUid",auth.getUid());m.put("reportedUid",uid);m.put("reason",reason);m.put("status","pending");m.put("createdAt",FieldValue.serverTimestamp());db.collection("reports").add(m).addOnSuccessListener(x->toast("Report sent to moderation.")).addOnFailureListener(x->toast("Report could not be sent."));}).setNegativeButton("Cancel",null).show();}
    private EditText inputDialog(String hint){EditText e=new EditText(this);e.setHint(hint);e.setPadding(20,10,20,10);return e;}
    private void block(String uid){Map<String,Object> m=new HashMap<>();m.put("blockedUid",uid);functions.getHttpsCallable("blockUser").call(m).addOnSuccessListener(x->{toast("User blocked and active connection closed.");home();}).addOnFailureListener(e->toast("Could not block this user."));}

    private void wali(){base();title("Family / Wali Connect");root.addView(text("Optional, consent-based family involvement. The other person must have a real Best Nikah Bridge account.",15,false));EditText e=input("Wali Firebase UID");Button b=button("Request Wali Connection",true),back=button("Back",false);b.setOnClickListener(x->{String uid=e.getText().toString().trim();if(uid.isEmpty()){e.setError("Enter Wali UID");return;}Map<String,Object> m=new HashMap<>();m.put("waliUid",uid);functions.getHttpsCallable("requestWaliConnection").call(m).addOnSuccessListener(y->toast("Wali request sent securely.")).addOnFailureListener(y->toast("Wali request failed. The Wali must have a real account."));});back.setOnClickListener(x->home());}
    private void safety(){base();title("Scam Shield & Safety");root.addView(text("BEST NIKAH BRIDGE SAFETY RULES\n\n• Never send money, gift cards or crypto.\n• Never share OTPs, passwords or recovery codes.\n• Do not send identity documents in chat.\n• Verification is not a guarantee.\n• Keep communication inside the app until trust is established.\n• Involve family/Wali for serious discussions.\n• Report pressure, threats, financial requests or suspicious behavior.\n• Blocking closes an active connection.\n• For threats or emergencies, contact local authorities.",17,false));Button b=button("Back",false);b.setOnClickListener(v->home());}
    private void verification(){base();title("Real Verification");root.addView(text("Verification requests are stored in Firebase and only authorized administration can approve or reject them.",15,false));EditText note=input("Verification note (do not enter sensitive ID numbers)");Button b=button("Submit Verification Request",true),back=button("Back",false);db.collection("users").document(auth.getUid()).get().addOnSuccessListener(d->root.addView(text("Current status: "+val(d,"verificationStatus"),18,true)));b.setOnClickListener(x->{Map<String,Object> m=new HashMap<>();m.put("userUid",auth.getUid());m.put("note",note.getText().toString().trim());m.put("status","pending");m.put("createdAt",FieldValue.serverTimestamp());db.collection("verifications").add(m).addOnSuccessListener(y->toast("Verification request submitted securely.")).addOnFailureListener(y->toast("Verification request failed."));});back.setOnClickListener(x->home());}
    private void help(){base();title("AI Nikah Assistant");root.addView(text("Real Gemini-powered guidance through Firebase AI Logic. It helps with respectful compatibility questions, family conversations, boundaries, safety and marriage planning. It does not issue religious rulings.",15,false));EditText q=input("Ask your Nikah question...");Button ask=button("Ask AI Nikah Assistant",true),quick=button("Generate compatibility questions",false),back=button("Back",false);TextView answer=text("",16,false);root.addView(answer);ask.setOnClickListener(v->{String prompt=q.getText().toString().trim();if(prompt.length()<4){q.setError("Ask a clear question");return;}runAI(prompt,answer);});quick.setOnClickListener(v->runAI("Create 8 respectful pre-Nikah compatibility questions covering deen, character, finances, family, children, location, conflict resolution and marriage timeline. Avoid judging or issuing a religious ruling.",answer));back.setOnClickListener(v->home());}
    private void runAI(String prompt,TextView answer){answer.setText("AI is preparing a response…");aiExecutor.execute(()->{try{GenerativeModel ai=FirebaseAI.getInstance(GenerativeBackend.googleAI()).generativeModel("gemini-3.7-flash");GenerativeModelFutures model=GenerativeModelFutures.from(ai);Content content=new Content.Builder().addText("You are the Best Nikah Bridge assistant. Be respectful, safety-first, family-aware and concise. This is a Muslim matrimonial app, not dating. Do not give fatwas or pretend to be a scholar. User request: "+prompt).build();ListenableFuture<GenerateContentResponse> future=model.generateContent(content);GenerateContentResponse response=future.get();String out=response.getText();if(out==null||out.trim().isEmpty())throw new IllegalStateException("Empty AI response");runOnUiThread(()->answer.setText(out));}catch(Exception e){runOnUiThread(()->answer.setText("AI is temporarily unavailable. Keep communication respectful, involve family/Wali, verify important claims independently, never send money or OTPs, and consult a qualified scholar for religious rulings."));}});}
    private void privacy(){base();title("Privacy Control Center");root.addView(text("Control whether your profile is discoverable and what location detail is shown to other members.",15,false));CheckBox discover=new CheckBox(this),cityVisible=new CheckBox(this);discover.setText("Show my profile in matching");cityVisible.setText("Show my city on my public profile");root.addView(discover);root.addView(cityVisible);Button save=button("Save Privacy Controls",true),back=button("Back",false);db.collection("users").document(auth.getUid()).get().addOnSuccessListener(d->{discover.setChecked(Boolean.TRUE.equals(d.getBoolean("discoverable")));cityVisible.setChecked(!Boolean.FALSE.equals(d.getBoolean("showCity")));});save.setOnClickListener(v->{Map<String,Object> m=new HashMap<>();m.put("discoverable",discover.isChecked());m.put("showCity",cityVisible.isChecked());m.put("privacyUpdatedAt",FieldValue.serverTimestamp());db.collection("users").document(auth.getUid()).set(m,SetOptions.merge()).addOnSuccessListener(x->toast("Privacy controls saved.")).addOnFailureListener(x->toast("Privacy controls could not be saved."));});back.setOnClickListener(v->home());}
    private void account(){base();title("Account & Privacy");root.addView(text("Account deletion is permanent. The trusted Firebase backend removes your profile and related account records. Sign out keeps the account.",16,false));Button d=button("Permanently Delete Account",true),out=button("Sign out",false),b=button("Back",false);d.setOnClickListener(x->new AlertDialog.Builder(this).setTitle("Delete account permanently?").setMessage("This cannot be undone. Your profile, interests and related records will be removed by the trusted backend.").setPositiveButton("Delete",(z,w)->deleteAccount()).setNegativeButton("Cancel",null).show());out.setOnClickListener(x->{auth.signOut();authScreen();});b.setOnClickListener(x->home());}
    private void deleteAccount(){functions.getHttpsCallable("deleteMyAccount").call(new HashMap<>()).addOnSuccessListener(x->{auth.signOut();toast("Account deleted permanently.");authScreen();}).addOnFailureListener(x->toast("Deletion failed. Please retry when online."));}
    private void terms(){new AlertDialog.Builder(this).setTitle("Terms & Community Rules").setMessage("Best Nikah Bridge is for serious marriage intentions. No harassment, scams, financial requests, impersonation, explicit content or misleading profiles. Respect privacy, family involvement and consent. Verification does not guarantee a person's character or intentions. Use report and block tools when needed. Global Community Chat is free but remains subject to these rules and moderation.").setPositiveButton("Close",null).show();}
}