package com.nikahbridge;

import android.app.Activity;import android.os.Bundle;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.Gravity;import android.widget.*;import org.json.JSONArray;import org.json.JSONObject;

public class NikahAssistantActivity extends Activity{
 EditText question;TextView answer;Button ask;final int green=Premium2030Ui.GREEN,dark=Premium2030Ui.TEXT,gray=Premium2030Ui.MUTED;
 public void onCreate(Bundle b){super.onCreate(b);AzureAuthManager.bindActivity(this);PremiumFeatureGate.require(this,"aiNikahAssistant","VIP 60 SAR",this::render);}
 TextView txt(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(bold?dark:gray);t.setPadding(6,8,6,10);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 Button btn(String s,boolean fill){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(fill?Color.WHITE:green);GradientDrawable g=new GradientDrawable();g.setColor(fill?green:Color.WHITE);g.setCornerRadius(18);if(!fill)g.setStroke(2,green);b.setBackground(g);return b;}
 void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,22,20,30);TextView h=txt("AI Nikah Assistant",27,true);h.setGravity(Gravity.CENTER);root.addView(h);root.addView(txt("Real Azure AI guidance for respectful marriage preparation, family communication, safety and compatibility. It does not issue religious rulings.",15,false));question=new EditText(this);question.setHint("Ask your Nikah question…");root.addView(question,new LinearLayout.LayoutParams(-1,130));ask=btn("Ask AI Nikah Assistant",true);root.addView(ask,new LinearLayout.LayoutParams(-1,62));answer=txt("Your Azure AI answer will appear here.",16,false);root.addView(answer);Button back=btn("Back",false);root.addView(back,new LinearLayout.LayoutParams(-1,62));back.setOnClickListener(v->finish());ask.setOnClickListener(v->askAI());setContentView(root);}
 void askAI(){String q=question.getText().toString().trim();if(q.isEmpty()){answer.setText("Please enter a question first.");return;}ask.setEnabled(false);answer.setText("Thinking…");try{JSONObject m=new JSONObject();m.put("role","user");m.put("content",q);JSONArray a=new JSONArray().put(m);JSONObject body=new JSONObject().put("messages",a);AzureApiClient.post("/ai/nikah-assistant",body.toString(),new AzureApiClient.Callback(){public void ok(int c,String s){runOnUiThread(()->{try{answer.setText(new JSONObject(s).getJSONObject("assistant").getString("content"));}catch(Exception e){answer.setText("Azure AI returned an invalid response.");}ask.setEnabled(true);});}public void err(String e){runOnUiThread(()->{answer.setText("Azure AI service is temporarily unavailable.");ask.setEnabled(true);});}});}catch(Exception e){ask.setEnabled(true);answer.setText("Could not prepare the request.");}}
}