package com.nikahbridge;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.widget.*;import com.google.firebase.auth.*;import com.google.firebase.firestore.*;import com.google.firebase.functions.FirebaseFunctions;import java.util.*;

public class ProductionMainActivity extends Activity{
 FirebaseAuth auth;FirebaseFirestore db;FirebaseFunctions fn;LinearLayout root;int green=Color.rgb(18,103,82),dark=Color.rgb(30,45,41),gray=Color.rgb(90,105,100);
 public void onCreate(Bundle b){super.onCreate(b);auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance();fn=FirebaseFunctions.getInstance();if(auth.getCurrentUser()==null)login();else home();}
 void base(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,30);s.addView(root);setContentView(s);}TextView t(String x,int z,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(b?dark:gray);v.setPadding(6,8,6,10);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}void title(String x){TextView v=t(x,27,true);v.setGravity(17);root.addView(v);}Button bt(String x,boolean fill){Button b=new Button(this);b.setText(x);b.setAllCaps(false);b.setTextSize(16);b.setTextColor(fill?Color.WHITE:green);GradientDrawable g=new GradientDrawable();g.setColor(fill?green:Color.WHITE);g.setCornerRadius(18);if(!fill)g.setStroke(2,green);b.setBackground(g);root.addView(b,new LinearLayout.LayoutParams(-1,62));return b;}EditText in(String h){EditText e=new EditText(this);e.setHint(h);root.addView(e,new LinearLayout.LayoutParams(-1,62));return e;}void toast(String x){Toast.makeText(this,x,Toast.LENGTH_LONG).show();}String val(DocumentSnapshot d,String k){Object x=d.get(k);return x==null?"":String.valueOf(x);}
 void login(){base();title("Best Nikah Bridge");root.addView(t("Real Firebase • Serious Nikah only • Not dating",16,false));EditText e=in("Email"),p=in("Password");Button s=bt("Sign in",true);s.setOnClickListener(v->auth.signInWithEmailAndPassword(e.getText().toString().trim(),p.getText().toString()).addOnSuccessListener(x->home()).addOnFailureListener(x->toast("Sign in failed.")));}
 void home(){base();title("Best Nikah Bridge");root.addView(t("Production feature baseline — real Firebase data only.",16,false));Button p=bt("My Profile",true),m=bt("Real Matches",true),i=bt("Mutual Interests & Safe Chat",true),f=bt("Family Bridge / Wali",true),n=bt("Nikah Promise Path",true),l=bt("Living Compatibility",true),h=bt("Connection Health Check",true),v=bt("Real Verification",false),s=bt("Scam Shield",false),o=bt("Sign out",false);p.setOnClickListener(x->profile());m.setOnClickListener(x->matches());i.setOnClickListener(x->interests());f.setOnClickListener(x->family());n.setOnClickListener(x->promise());l.setOnClickListener(x->living());h.setOnClickListener(x->health());v.setOnClickListener(x->verification());s.setOnClickListener(x->safety());o.setOnClickListener(x->{auth.signOut();login();});}
 void profile(){base();title("Real Nikah Profile");EditText name=in("Full name"),age=in("Age"),country=in("Country"),city=in("City"),intent=in("Marriage intention"),timeline=in("Marriage timeline"),family=in("Family/Wali preference"),deal=in("Deal-breakers"),about=in("About");Button save=bt("Save & Activate",true),back=bt("Back",false);save.setOnClickListener(x->{Map<String,Object> q=new HashMap<>();q.put("uid",auth.getUid());q.put("name",name.getText().toString());try{q.put("age",Integer.parseInt(age.getText().toString()));}catch(Exception e){toast("Age required.");return;}q.put("country",country.getText().toString());q.put("city",city.getText().toString());q.put("marriageIntent",intent.getText().toString());q.put("marriageTimeline",timeline.getText().toString());q.put("familyInvolvement",family.getText().toString());q.put("dealbreakers",deal.getText().toString());q.put("about",about.getText().toString());q.put("profileActive",true);q.put("discoverable",true);q.put("termsAccepted",true);q.put("intentConfirmed",true);db.collection("users").document(auth.getUid()).set(q,SetOptions.merge()).addOnSuccessListener(y->{toast("Real profile activated.");home();});});back.setOnClickListener(x->home());}
 void matches(){base();title("Real Matches");db.collection("users").whereEqualTo("profileActive",true).whereEqualTo("discoverable",true).limit(50).get().addOnSuccessListener(q->{for(DocumentSnapshot d:q)if(!d.getId().equals(auth.getUid())){root.addView(t(val(d,"name")+" • "+val(d,"age")+" • "+val(d,"country"),19,true));root.addView(t("Why matched: marriage intent • timeline • family • location",14,false));Button b=bt("Express Interest",true);b.setOnClickListener(x->{Map<String,Object> z=new HashMap<>();z.put("targetUid",d.getId());fn.getHttpsCallable("sendInterest").call(z).addOnSuccessListener(y->toast("Interest sent securely."));});}});Button b=bt("Back",false);b.setOnClickListener(x->home());}
 void interests(){base();title("Mutual Interests & Safe Chat");root.addView(t("Private chat is available only after mutual acceptance.",15,false));db.collection("interests").whereEqualTo("toUid",auth.getUid()).whereEqualTo("status","pending").get().addOnSuccessListener(q->{for(DocumentSnapshot d:q){String id=d.getId(),from=val(d,"fromUid");Button a=bt("Accept • "+from,true);a.setOnClickListener(x->{db.collection("interests").document(id).update("status","accepted").addOnSuccessListener(y->{Map<String,Object> z=new HashMap<>();z.put("otherUid",from);fn.getHttpsCallable("createMutualConnection").call(z).addOnSuccessListener(k->{toast("Mutual connection active.");interests();});});});}});db.collection("connections").whereEqualTo("uid1",auth.getUid()).whereEqualTo("status","active").get().addOnSuccessListener(this::connectionList);db.collection("connections").whereEqualTo("uid2",auth.getUid()).whereEqualTo("status","active").get().addOnSuccessListener(this::connectionList);Button b=bt("Back",false);b.setOnClickListener(x->home());}
 void connectionList(QuerySnapshot q){for(DocumentSnapshot d:q){String other=auth.getUid().equals(val(d,"uid1"))?val(d,"uid2"):val(d,"uid1");Button b=bt("Open Safe Chat • "+other,true);b.setOnClickListener(x->chat(d.getId(),other));}}
 void chat(String cid,String other){base();title("Safe Private Chat");root.addView(t("Mutual-only. Two-message gate is enforced by production backend.",14,false));LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);EditText e=in("Message");Button send=bt("Send",true),back=bt("Back",false);Runnable load=()->db.collection("connections").document(cid).collection("messages").orderBy("sentAt",Query.Direction.ASCENDING).limitToLast(100).get().addOnSuccessListener(q->{list.removeAllViews();for(DocumentSnapshot d:q)list.addView(t((auth.getUid().equals(val(d,"fromUid"))?"You: ":"Them: ")+val(d,"text"),15,false));});send.setOnClickListener(x->{Map<String,Object> z=new HashMap<>();z.put("toUid",other);z.put("text",e.getText().toString().trim());fn.getHttpsCallable("sendConnectionMessage").call(z).addOnSuccessListener(y->{e.setText("");load.run();}).addOnFailureListener(y->toast("Message blocked by mutual/two-message rule."));});back.setOnClickListener(x->interests());load.run();}
 void family(){base();title("Family Bridge / Wali");EditText cid=in("Mutual connection ID"),wali=in("Family/Wali Firebase UID");Button c=bt("Create Family Bridge",true),q=bt("Send Family Question",false),b=bt("Back",false);c.setOnClickListener(x->{Map<String,Object> z=new HashMap<>();z.put("connectionId",cid.getText().toString());z.put("familyUid",wali.getText().toString());fn.getHttpsCallable("createFamilyBridge").call(z).addOnSuccessListener(y->toast("Family Bridge created securely."));});q.setOnClickListener(x->{EditText e=new EditText(this);e.setHint("Question");new AlertDialog.Builder(this).setTitle("Question Bridge").setView(e).setPositiveButton("Send",(d,w)->{Map<String,Object> z=new HashMap<>();z.put("bridgeId",cid.getText().toString());z.put("text",e.getText().toString());fn.getHttpsCallable("sendFamilyQuestion").call(z).addOnSuccessListener(y->toast("Question sent securely."));}).setNegativeButton("Cancel",null).show();});b.setOnClickListener(x->home());}
 void promise(){base();title("Nikah Promise Path");EditText cid=in("Mutual connection ID"),stage=in("Stage"),date=in("Target date"),notes=in("Notes");Button s=bt("Save Real Roadmap",true),b=bt("Back",false);s.setOnClickListener(x->{Map<String,Object> z=new HashMap<>();z.put("connectionId",cid.getText().toString());z.put("stage",stage.getText().toString());z.put("targetDate",date.getText().toString());z.put("notes",notes.getText().toString());fn.getHttpsCallable("setNikahPromise").call(z).addOnSuccessListener(y->toast("Roadmap saved to Firebase."));});b.setOnClickListener(x->home());}
 void living(){base();title("Living Compatibility");EditText c=in("Country"),city=in("City"),time=in("Marriage timeline"),fam=in("Family involvement"),child=in("Children expectations"),career=in("Career plan"),plan=in("Living plan");Button s=bt("Save Real Changes",true),b=bt("Back",false);s.setOnClickListener(x->{Map<String,Object> z=new HashMap<>();z.put("country",c.getText().toString());z.put("city",city.getText().toString());z.put("marriageTimeline",time.getText().toString());z.put("familyInvolvement",fam.getText().toString());z.put("childrenExpectation",child.getText().toString());z.put("careerPlan",career.getText().toString());z.put("livingPlan",plan.getText().toString());fn.getHttpsCallable("updateLivingCompatibility").call(z).addOnSuccessListener(y->toast("Living Compatibility saved."));});b.setOnClickListener(x->home());}
 void health(){base();title("Connection Health Check");EditText cid=in("Mutual connection ID"),c=in("Communication comfort"),f=in("Family progress"),d=in("Unresolved differences"),t=in("Timeline aligned?");Button s=bt("Save Private Check",true),b=bt("Back",false);s.setOnClickListener(x->{Map<String,Object> z=new HashMap<>();z.put("connectionId",cid.getText().toString());z.put("communication",c.getText().toString());z.put("familyProgress",f.getText().toString());z.put("unresolvedDifferences",d.getText().toString());z.put("timelineAligned",t.getText().toString());fn.getHttpsCallable("saveHealthCheck").call(z).addOnSuccessListener(y->toast("Private health check saved."));});b.setOnClickListener(x->home());}
 void verification(){base();title("Real Verification");EditText n=in("Verification note — no sensitive ID numbers");Button s=bt("Submit Request",true),b=bt("Back",false);s.setOnClickListener(x->{Map<String,Object> z=new HashMap<>();z.put("userUid",auth.getUid());z.put("note",n.getText().toString());z.put("status","pending");z.put("createdAt",FieldValue.serverTimestamp());db.collection("verifications").add(z).addOnSuccessListener(y->toast("Verification request submitted."));});b.setOnClickListener(x->home());}
 void safety(){base();title("Scam Shield");root.addView(t("Never send money, OTPs, passwords or crypto. Never share identity documents in chat. Verification is not a guarantee. Report pressure, threats, impersonation and financial requests. Involve family/Wali for serious discussions.",16,false));Button b=bt("Back",false);b.setOnClickListener(x->home());}
}
