package com.nikahbridge;
import android.app.Activity;import android.os.Bundle;import android.graphics.Color;import android.widget.*;import com.google.firebase.auth.FirebaseAuth;import com.google.firebase.functions.FirebaseFunctions;import java.util.*;
/** Real admin verification queue/review screen. Backend enforces admin claim. */
public class VerificationAdminActivity extends Activity{
 FirebaseAuth auth;FirebaseFunctions fn;LinearLayout list;TextView status;
 public void onCreate(Bundle b){super.onCreate(b);auth=FirebaseAuth.getInstance();fn=FirebaseFunctions.getInstance();build();load();}
 TextView t(String s){TextView x=new TextView(this);x.setText(s);x.setTextSize(16);x.setTextColor(Color.rgb(30,45,41));x.setPadding(8,12,8,12);return x;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}
 void build(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(18,20,18,25);sc.addView(r);setContentView(sc);r.addView(t("Identity Verification — Admin Review"));status=t("Status: loading…");r.addView(status);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);Button refresh=b("Refresh Queue");refresh.setOnClickListener(v->load());r.addView(refresh);Button back=b("Back");back.setOnClickListener(v->finish());r.addView(back);}
 void load(){if(auth.getCurrentUser()==null){status.setText("Sign in required");return;}status.setText("Status: loading pending requests…");fn.getHttpsCallable("listPendingVerifications").call(new HashMap<>()).addOnSuccessListener(r->{list.removeAllViews();status.setText("Status: pending queue loaded");Object raw=r.getData();if(raw instanceof Map){Object items=((Map)raw).get("items");if(items instanceof List)for(Object o:(List)items)add(o);}}).addOnFailureListener(e->status.setText("Status: admin access required or queue unavailable"));}
 void add(Object o){if(!(o instanceof Map))return;Map m=(Map)o;String uid=String.valueOf(m.get("uid"));String type=String.valueOf(m.get("documentType"));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.addView(t("UID: "+uid+"\nDocument: "+type));Button ok=b("Approve / Verify");Button no=b("Reject");row.addView(ok);row.addView(no);list.addView(row);ok.setOnClickListener(v->review(uid,"verified"));no.setOnClickListener(v->review(uid,"rejected"));}
 void review(String uid,String decision){Map<String,Object>d=new HashMap<>();d.put("userUid",uid);d.put("decision",decision);d.put("reviewNote",decision.equals("verified")?"Identity document reviewed and verified.":"Identity document was not accepted; user may resubmit after correcting the issue.");fn.getHttpsCallable("reviewIdentityVerification").call(d).addOnSuccessListener(x->load()).addOnFailureListener(e->Toast.makeText(this,"Review failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}
}
