package com.nikahbridge;

import android.app.Activity;
import android.app.AlertDialog;
import android.os.Bundle;
import android.graphics.Color;
import android.content.Intent;
import android.widget.*;
import java.util.Locale;

public class WalletActivity extends Activity {
    private LinearLayout root;
    private TextView balance;
    private int dp(int value){ return (int)(value * getResources().getDisplayMetrics().density + 0.5f); }
    private void add(String s,int size,boolean bold){ TextView t=new TextView(this); t.setText(s); t.setTextSize(size); t.setTextColor(bold?Color.rgb(30,45,41):Color.rgb(95,108,103)); t.setPadding(dp(8),dp(10),dp(8),dp(10)); if(bold)t.setTypeface(null,1); root.addView(t); }
    private Button btn(String s){ Button b=new Button(this); b.setText(s); b.setAllCaps(false); b.setTextSize(16); b.setTextColor(Color.rgb(18,103,82)); root.addView(b,new LinearLayout.LayoutParams(-1,dp(62))); return b; }
    @Override protected void onCreate(Bundle state){ super.onCreate(state); ScrollView sv=new ScrollView(this); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(dp(22),dp(24),dp(22),dp(30)); sv.addView(root); setContentView(sv); add("Best Nikah Bridge Wallet",28,true); add("Real Azure wallet ledger. Balances come only from authenticated Azure ledger records and verified transactions.",15,false); balance=new TextView(this); balance.setTextSize(22); balance.setTextColor(Color.rgb(30,45,41)); balance.setPadding(dp(8),dp(16),dp(8),dp(16)); root.addView(balance); Button refresh=btn("Refresh Wallet"); Button premium=btn("Premium Plans — 20 / 40 / 60 SAR"); Button withdraw=btn("Request Withdrawal"); Button history=btn("Transaction History"); Button owner=btn("Owner Earnings & Settlement"); Button back=btn("Back"); refresh.setOnClickListener(v->load()); premium.setOnClickListener(v->startActivity(new Intent(this,PremiumPlansActivity.class))); withdraw.setOnClickListener(v->withdrawDialog()); history.setOnClickListener(v->history()); owner.setOnClickListener(v->startActivity(new Intent(this,OwnerEarningsActivity.class))); back.setOnClickListener(v->finish()); load(); }
    private void load(){ AzureWalletApi.get("/wallet",new AzureWalletApi.Callback(){public void onSuccess(String body){runOnUiThread(()->balance.setText(body));}public void onError(String e){runOnUiThread(()->balance.setText("Azure wallet unavailable: "+e));}}); }
    private void withdrawDialog(){ LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); EditText amount=new EditText(this); amount.setHint("Amount (10.00 minimum)"); EditText currency=new EditText(this); currency.setHint("Currency: SAR or USDT"); currency.setText("SAR"); EditText country=new EditText(this); country.setHint("Country"); EditText destination=new EditText(this); destination.setHint("Real payout destination / account"); box.addView(amount,new LinearLayout.LayoutParams(-1,dp(56)));box.addView(currency,new LinearLayout.LayoutParams(-1,dp(56)));box.addView(country,new LinearLayout.LayoutParams(-1,dp(56)));box.addView(destination,new LinearLayout.LayoutParams(-1,dp(56))); LanguageManager.dialog(this).setTitle("Real Withdrawal Request").setView(box).setMessage("Withdrawal requires verified identity/KYC and is sent to a real payout provider only after review.").setPositiveButton("Submit",(d,w)->{String a=amount.getText().toString().trim();String c=currency.getText().toString().trim().toUpperCase(Locale.US);String countryValue=country.getText().toString().trim();String dest=destination.getText().toString().trim();String json="{\"amount\":"+quote(a)+",\"currency\":"+quote(c)+",\"country\":"+quote(countryValue)+",\"destination\":"+quote(dest)+"}"; AzureWalletApi.post("/wallet/withdrawals",json,new AzureWalletApi.Callback(){public void onSuccess(String body){runOnUiThread(()->{LanguageManager.dialog(WalletActivity.this).setTitle("Withdrawal submitted").setMessage(body).setPositiveButton("OK",null).show();load();});}public void onError(String e){runOnUiThread(()->LanguageManager.dialog(WalletActivity.this).setTitle("Withdrawal not submitted").setMessage(e).setPositiveButton("OK",null).show());}});}).setNegativeButton("Cancel",null).show(); }
    private String quote(String value){return "\\\""+value.replace("\\","\\\\").replace("\\\"","\\\\\"")+"\\\"";}
    private void history(){ AzureWalletApi.get("/wallet/transactions",new AzureWalletApi.Callback(){public void onSuccess(String body){runOnUiThread(()->LanguageManager.dialog(WalletActivity.this).setTitle("Azure Wallet Transactions").setMessage(body).setPositiveButton("Close",null).show());}public void onError(String e){runOnUiThread(()->LanguageManager.dialog(WalletActivity.this).setTitle("History unavailable").setMessage(e).setPositiveButton("Close",null).show());}}); }
}
