name: Create Android Keystore

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Generate release keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore release-key.jks \
            -alias bestnikahbridge \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass tempPassword123 \
            -keypass tempPassword123 \
            -dname "CN=Best Nikah Bridge, OU=Mobile, O=Best Nikah Bridge, L=Jeddah, ST=Makkah, C=SA"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: best-nikah-bridge-keystore
          path: release-key.jks
