name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x gradlew
    
      - name: Build Release AAB
        run: ./gradlew :app:bundleRelease

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: best-nikah-bridge-release-aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: best-nikah-bridge-release-apk
          path: app/build/outputs/apk/release/app-release.apk
